### ISSUE TITLE
Cmake is not stalled 

### ISSUE THREAD

**Issue by xinyu998** [mkhaled87/pFaces-OmegaThreads#1]
Hi, I tried to run this in my Mac terminal and When I entered "sh build.sh", it showed CMAKE is not installed. Please install it first. I have CMAKE in my MacBook, as well as docker. So I don't understand what causes this bug. Is there anything else I need to do except for just cloning those codes to Terminal?
Thank you!
<img width="493" alt="Screen Shot 2021-11-29 at 17 44 24" src="https://user-images.githubusercontent.com/90066159/143954443-f71621e9-5cea-4f9e-8faf-270edb4bfae2.png">
.

**Comment by mkhaled87** [comment]
Sorry just saw this now (after almost a year!) This is already fixed in one of the commits.
